name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verify files exist
        run: |
          if [ ! -f "install-nerd-fonts.sh" ]; then
            echo "Error: install-nerd-fonts.sh not found"
            exit 1
          fi
          if [ ! -f "README.md" ]; then
            echo "Error: README.md not found"
            exit 1
          fi
          echo "Files verified successfully"
          ls -la install-nerd-fonts.sh README.md
      
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Creating release for version: $VERSION"
      
      - name: Update README version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          # Update version in README installation instructions
          sed -i "s|/releases/download/v[0-9.]\+/|/releases/download/$VERSION/|g" README.md
          echo "Updated README with version: $VERSION"
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            ## Installation
            ```bash
            curl -o install-nerd-fonts.sh https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/install-nerd-fonts.sh
            chmod +x install-nerd-fonts.sh
            ./install-nerd-fonts.sh
            ```
            
            ## Changes
            - Added backup functionality with timestamped backups
            - Improved profile handling with better formatting
            - Enhanced profile display and listing
            - Better cross-platform compatibility
            - Added proper error handling
            - Fixed font cache refresh commands
          draft: false
          prerelease: false
          artifacts: "install-nerd-fonts.sh,README.md"
          allowUpdates: true

      - name: Verify Release
        run: |
          echo "Waiting for release to be available..."
          sleep 15
          VERSION=${GITHUB_REF#refs/tags/}
          ASSET_URL="https://github.com/${{ github.repository }}/releases/download/$VERSION/install-nerd-fonts.sh"
          echo "Checking asset at: $ASSET_URL"
          curl -sSf -o /dev/null "$ASSET_URL" || {
            echo "Error: Release asset not accessible"
            exit 1
          }
          echo "Release verified successfully"
